### ISSUE TITLE
Project creation from this template complains about vulnerabilities 

### ISSUE THREAD

**Issue by daniel-j-h** [preactjs-templates/typescript#68]
Hey folks, when I create a new project from this template, I get lots of warnings for moderate and high security vulnerabilities.

Can we update all dependencies to their latest version, or is there a reason behind being on specific versions?

```
/app # preact create typescript test
ℹ INFO Assuming you meant preactjs-templates/typescript...
  Installing dependencies:

npm WARN ERESOLVE overriding peer dependency
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/req
uest/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See
 https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See
 https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 2095 packages, and audited 2096 packages in 38s

164 packages are looking for funding
  run `npm fund` for details

24 vulnerabilities (17 moderate, 7 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

it also looks like some deps are outdated; is this related?

```
/app/test # npm outdated
Package                           Current   Wanted  Latest  Location                                       Depended by
@types/jest                       26.0.24  26.0.24  27.4.0  node_modules/@types/jest                       test
@typescript-eslint/eslint-plugin   2.34.0   2.34.0   5.8.1  node_modules/@typescript-eslint/eslint-plugin  test
@typescript-eslint/parser          2.34.0   2.34.0   5.8.1  node_modules/@typescript-eslint/parser         test
eslint                              6.8.0    6.8.0   8.5.0  node_modules/eslint                            test
sirv-cli                           1.0.14   1.0.14   2.0.1  node_modules/sirv-cli                          test
```

**Comment by rschristian** [comment]
> I get lots of warnings for moderate and high security vulnerabilities.

Most should be ignored. `npm audit` is famously broken by design, and unless you know what you're looking for, is something that should be disabled. `preact-cli` includes both a dev and production environment, yet `npm audit` will treat them both as if they are public-facing. The fact that someone can DDOS your dev server due to a "vulnerability" is incredibly irrelevant.

[Great article on this](https://overreacted.io/npm-audit-broken-by-design/) if you want to read more.

We're generally up-to-date on dependencies, but if you see something that needs a bump, feel free to open a PR against `preact-cli`. 

> Can we update all dependencies to their latest version, or is there a reason behind being on specific versions?

Just about everything is latest. If things we rely on end up relying on deprecated packages, that's largely beyond our control.

Looking at that list, we're attempting to update `html-webpack-plugin`, but blocked by another dependency that's a bit broken at the moment. Once that's corrected, bumping the troublesome dependency will also correct `svgo` I believe.

> it also looks like some deps are outdated; is this related?

Deps in the template are things you can bump yourself. Keeping the templates up-to-date with the latest major would be a large amount of work for the minimal team. It's mostly just busy work too. An out-of-date ESLint config isn't going to cause any issues. `sirv-cli`, for example, just hit 2.0.0 two days ago.

**Comment by daniel-j-h** [comment]
Thanks for taking the time to explain the situation to me and thanks for sharing the npm audit article.

I have disabled npm audit now through a .npmrc file to silence the noise :see_no_evil: :hear_no_evil: :speak_no_evil: 

I'll close here since it sounds like you folks are on it.

**Comment by rschristian** [comment]
Forgot to mention, but disabling the automatic audit on install tends to have a pretty good impact on install times, which is a nice bonus!
